// setup status actions
export const CREATE_INITIAL_PLAYER = "CREATE_INITIAL_PLAYER";
export const GET_PLAYER = "GET_PLAYER";
export const GET_PLAYER_STATS = "GET_STATS";
export const UPDATE_STAT = "UPDATE_STAT";
export const UPDATE_PLAYER_PERKS = "UPATE_PLAYER_PERKS";

export const CREATE_INITIAL_PERKS = "CREATE_INITIAL_PERKS";
